[build]
publish = "public"
command = "./stackbit-build.sh"

  [build.environment]
  HUGO_VERSION = "0.47"

[[plugins]]
package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  buildDir = "public"
  # disable pretty URLS and keep `index.html` & trailing `.html` file references in paths
  prettyURLs = true
  
[[redirects]]
  from = "/azimo"
  to = "https://azimo.com/en/invitation?code=ARTURASU1"
  status = 301
  force = true
[[redirects]]
  from = "/az"
  to = "https://azimo.com/en/invitation?code=ARTURASU1"
  status = 301
  force = true
[[redirects]]
  from = "/worldremit"
  to = "https://www.worldremit.com/en/r/ARTURASU1"
  status = 301
  force = true
[[redirects]]
  from = "/wr"
  to = "https://www.worldremit.com/en/r/ARTURASU1"
  status = 301
  force = true
[[redirects]]
  from = "/transfergo"
  to = "http://trgo.co/en/r/dreamtrue"
  status = 301
  force = true
[[redirects]]
  from = "/tg"
  to = "http://trgo.co/en/r/dreamtrue"
  status = 301
  force = true
[[redirects]]
  from = "/transferwise"
  to = "https://transferwise.com/invite/u/arturasu5"
  status = 301
  force = true
[[redirects]]
  from = "/tw"
  to = "https://transferwise.com/invite/u/arturasu5"
  status = 301
  force = true
[[redirects]]
  from = "/bitwala"
  to = "http://app.bitwala.com/r/aZMTF-LU"
  status = 301
  force = true
[[redirects]]
  from = "/bw"
  to = "http://app.bitwala.com/r/aZMTF-LU"
  status = 301
  force = true
[[redirects]] 
  from = "/bitpanda"
  to = "https://www.bitpanda.com/en?ref=990354243165719653"
  status = 301
  force = true
[[redirects]] 
  from = "/bp"
  to = "https://www.bitpanda.com/en?ref=990354243165719653"
  status = 301
  force = true
[[redirects]]
  from = "/xendpay"
  to = "https://secure.xendpay.com/signup/ur/S293991"
  status = 301
  force = true
[[redirects]]
  from = "/xp"
  to = "https://secure.xendpay.com/signup/ur/S293991"
  status = 301
  force = true
[[redirects]]
  from = "/skrill"
  to = "https://transfers.skrill.com/smt/refer/code/arturasu13"
  status = 301
  force = true
[[redirects]]
  from = "/sk"
  to = "https://transfers.skrill.com/smt/refer/code/arturasu13"
  status = 301
  force = true
[[redirects]]
  from = "/vimba"
  to = "https://vimba.co?referrer=X3ZEZbWL"
  status = 301
  force = true
[[redirects]]
  from = "/vm"
  to = "https://vimba.co?referrer=X3ZEZbWL"
  status = 301
  force = true
[[redirects]]
  from = "/mercury"
  to = "https://dashboard.mercury.cash/register?referal=4976b02ca0404af0826cf834d8e52757"
  status = 301
  force = true
[[redirects]]
  from = "/mc"
  to = "https://dashboard.mercury.cash/register?referal=4976b02ca0404af0826cf834d8e52757"
  status = 301
  force = true
[[redirects]]
  from = "/xapo"
  to = "https://get.xapo.com/9GJF3"
  status = 301
  force = true
[[redirects]]
  from = "/xp"
  to = "https://get.xapo.com/9GJF3"
  status = 301
  force = true  
 
