[build]
publish = "public"
command = "./stackbit-build.sh"

  [build.environment]
  HUGO_VERSION = "0.47"

[[plugins]]
package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  buildDir = "public"
  # disable pretty URLS and keep `index.html` & trailing `.html` file references in paths
  prettyURLs = true
  
[[plugins]]
package = "netlify-plugin-subfont"

  [plugins.inputs]
  # An array of glob patterns for pages on your site
  # Recursive traversal will start from these
  entryPoints = [
    "*.html",
  ]

  # Follow your links across all pages to optimize the fonts across the entire site
  recursive = true

  # Subfont lets you set CSS font-display value of the optimized subsets
  # See https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display
  fontDisplay = "swap"

  # Inline generated CSS @font-face blocks into each page
  # When set to `false` an external CSS file will be created
  inlineCss = false

  # Inline generated font subsets into their respective @font-face blocks
  # When set to `false` external font files will be created
  inlineFonts = false

  # Include fallbacks so the original font will be loaded when dynamic content gets injected at runtime
  # When set to `false` external font files will be created
  fallbacks = true
  
[[redirects]]
  from = "/cms"
  to = "https://ism.admin.datocms.com"
  status = 301
  force = true
  
[[redirects]]
  from = "/azimo"
  to = "https://azimo.com/en/invitation?code=ARTURASU1"
  status = 301
  force = true
[[redirects]]
  from = "/az"
  to = "https://azimo.com/en/invitation?code=ARTURASU1"
  status = 301
  force = true
[[redirects]]
  from = "/worldremit"
  to = "https://www.worldremit.com/en/r/ARTURASU1"
  status = 301
  force = true
[[redirects]]
  from = "/wr"
  to = "https://www.worldremit.com/en/r/ARTURASU1"
  status = 301
  force = true
[[redirects]]
  from = "/transfergo"
  to = "http://trgo.co/en/r/dreamtrue"
  status = 301
  force = true
[[redirects]]
  from = "/tg"
  to = "http://trgo.co/en/r/dreamtrue"
  status = 301
  force = true
[[redirects]]
  from = "/transferwise"
  to = "https://transferwise.com/invite/u/arturasu5"
  status = 301
  force = true
[[redirects]]
  from = "/tw"
  to = "https://transferwise.com/invite/u/arturasu5"
  status = 301
  force = true
[[redirects]]
  from = "/bitwala"
  to = "http://app.bitwala.com/r/aZMTF-LU"
  status = 301
  force = true
[[redirects]]
  from = "/bw"
  to = "http://app.bitwala.com/r/aZMTF-LU"
  status = 301
  force = true
[[redirects]] 
  from = "/bitpanda"
  to = "https://www.bitpanda.com/en?ref=990354243165719653"
  status = 301
  force = true
[[redirects]] 
  from = "/bp"
  to = "https://www.bitpanda.com/en?ref=990354243165719653"
  status = 301
  force = true
[[redirects]]
  from = "/xendpay"
  to = "https://secure.xendpay.com/signup/ur/S293991"
  status = 301
  force = true
[[redirects]]
  from = "/xp"
  to = "https://secure.xendpay.com/signup/ur/S293991"
  status = 301
  force = true
[[redirects]]
  from = "/skrill"
  to = "https://transfers.skrill.com/smt/refer/code/arturasu13"
  status = 301
  force = true
[[redirects]]
  from = "/sk"
  to = "https://transfers.skrill.com/smt/refer/code/arturasu13"
  status = 301
  force = true
[[redirects]]
  from = "/vimba"
  to = "https://vimba.co?referrer=X3ZEZbWL"
  status = 301
  force = true
[[redirects]]
  from = "/vm"
  to = "https://vimba.co?referrer=X3ZEZbWL"
  status = 301
  force = true
[[redirects]]
  from = "/mercury"
  to = "https://ishare.money/links"
  status = 301
  force = true
[[redirects]]
  from = "/mc"
  to = "https://dashboard.mercury.cash/register?referal=4976b02ca0404af0826cf834d8e52757"
  status = 301
  force = true
[[redirects]]
  from = "/xapo"
  to = "https://get.xapo.com/9GJF3"
  status = 301
  force = true
[[redirects]]
  from = "/xa"
  to = "https://get.xapo.com/9GJF3"
  status = 301
  force = true  
[[redirects]]
  from = "/coinlist"
  to = "https://coinlist.co/clt?referral_code=9KHAD2"
  status = 301
  force = true
[[redirects]]
  from = "/cl"
  to = "https://coinlist.co/clt?referral_code=9KHAD2"
  status = 301
  force = true 
[[redirects]]
  from = "/quidco"
  to = "https://www.quidco.com/raf/10144159/"
  status = 301
  force = true
[[redirects]]
  from = "/qc"
  to = "https://www.quidco.com/raf/10144159/"
  status = 301
  force = true 
[[redirects]]
  from = "/aximetria"
  to = "https://aximetria.com/sl/"
  status = 301
  force = true
[[redirects]]
  from = "/ax"
  to = "https://aximetria.com/sl/"
  status = 301
  force = true 
[[redirects]]
  from = "/vivid"
  to = "https://vivid.money/r/arturasNBH/"
  status = 301
  force = true
[[redirects]]
  from = "/vi"
  to = "https://vivid.money/r/arturasNBH/"
  status = 301
  force = true 
[[redirects]]
  from = "/xlm"
  to = "https://coinbase.com/earn/xlm/invite/6yqc0mkt"
  status = 301
  force = true
[[redirects]]
  from = "/eos"
  to = "https://coinbase.com/earn/eos/invite/z6d4j1py"
  status = 301
  force = true
[[redirects]]
  from = "/comp"
  to = "https://www.coinbase.com/earn/compound/invite/1nswm0hq"
  status = 301
  force = true  
[[redirects]]
  from = "/test"
  to = "https://ishare.money/track/test/?utm_source=Topparrain&utm_medium=referral&utm_campaign=XML"
  status = 301
  force = true
[[redirects]]
  from = "/track/test/"
  to = "https://www.coinbase.com/earn/compound/invite/1nswm0hq"
  status = 301
  force = true
